# Generated by Django 4.1.9 on 2023-05-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('number_of_cylinders', models.IntegerField()),
                ('number_of_passengers', models.IntegerField()),
                ('car_color', models.CharField(max_length=255)),
                ('cylinder_volume', models.FloatField()),
                ('owner_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
